# -*- coding: utf-8 -*-
"""qlora_bash_commands_finetune.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hX_83Web0MiEvshTmdYShpWmGd4ZUfK4
"""

!pip install -q -U "bitsandbytes>=0.46.1"

import torch, bitsandbytes as bnb
print("bitsandbytes:", bnb.__version__)
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "none")

import torch

print("Torch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    BF16_SUPPORTED = torch.cuda.is_bf16_supported()
else:
    raise RuntimeError(
        "No GPU detected. Go to Runtime -> Change runtime type -> T4 GPU, then re-run this cell."
    )

print("bf16 supported on this GPU:", BF16_SUPPORTED)
# T4 -> False (uses fp16). A100/L4/H100 -> True (uses bf16). The rest adapts automatically.

MODEL_NAME = "Qwen/Qwen2.5-1.5B-Instruct"   # ungated, small, runs fine on a free T4. Swap for your own base model.
DATASET_NAME = "aelhalili/bash-commands-dataset"
OUTPUT_DIR = "qlora-bash-commands"
MAX_SEQ_LEN = 256                            # prompts/responses in this dataset are short
SYSTEM_PROMPT = (
    "You are a helpful assistant that converts natural language instructions "
    "into a single correct Bash command. Reply with only the command, no explanation."
)

from datasets import load_dataset

raw_dataset = load_dataset(DATASET_NAME, split="train")
print(raw_dataset)
print(raw_dataset[0])

import pandas as pd
from datasets import Dataset

df = raw_dataset.to_pandas()
before = len(df)
df = df.drop_duplicates(subset=["prompt", "response"]).reset_index(drop=True)
print(f"Removed {before - len(df)} duplicate rows -> {len(df)} unique examples remain")

dataset = Dataset.from_pandas(df, preserve_index=False)
split_dataset = dataset.train_test_split(test_size=0.1, seed=42)
train_dataset = split_dataset["train"]
eval_dataset = split_dataset["test"]
print(train_dataset)
print(eval_dataset)

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

def format_example(example):
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": example["prompt"]},
        {"role": "assistant", "content": example["response"]},
    ]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)
    return {"text": text}

train_dataset = train_dataset.map(format_example)
eval_dataset = eval_dataset.map(format_example)

print(train_dataset[0]["text"])

from transformers import AutoModelForCausalLM, BitsAndBytesConfig

compute_dtype = torch.bfloat16 if BF16_SUPPORTED else torch.float16

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=compute_dtype,
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
)
model.config.use_cache = False
model.config.pretraining_tp = 1

from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=True)

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

!pip -q install trl

from trl import SFTConfig, SFTTrainer

# Remove original columns to prevent SFTTrainer from trying to auto-tokenize 'prompt' and 'response'
clean_train_dataset = train_dataset.remove_columns(["prompt", "response"])
clean_eval_dataset = eval_dataset.remove_columns(["prompt", "response"])

sft_config = SFTConfig(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=4,
    num_train_epochs=5,
    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    logging_steps=10,
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,
    load_best_model_at_end=True,
    bf16=BF16_SUPPORTED,
    fp16=not BF16_SUPPORTED,
    optim="paged_adamw_8bit",
    report_to="none",
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    dataset_text_field="text",
    packing=False,
    max_length=MAX_SEQ_LEN,
)

# Safely set warmup_ratio if needed
sft_config.warmup_ratio = 0.03

trainer = SFTTrainer(
    model=model,
    args=sft_config,
    train_dataset=clean_train_dataset,
    eval_dataset=clean_eval_dataset,
    processing_class=tokenizer,
)

trainer.train()

trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
print("Saved LoRA adapter to:", OUTPUT_DIR)

model.config.use_cache = True
model.eval()

def ask(prompt, max_new_tokens=64):
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": prompt},
    ]
    input_text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(input_text, return_tensors="pt").to(model.device)
    with torch.no_grad():
        outputs = model.generate(**inputs, max_new_tokens=max_new_tokens, do_sample=False)
    return tokenizer.decode(outputs[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True).strip()

for p in [
    "Show me all hidden files in my home directory",
    "Compress the folder called reports into a zip file",
    "Show the top 5 memory-consuming processes",
]:
    print(f"PROMPT: {p}")
    print(f"MODEL:  {ask(p)}")
    print("-" * 60)

# 1. Upgrade torchao to resolve the compatibility issue with PEFT, then merge the LoRA adapter
!pip install -q -U torchao

import torch
from peft import AutoPeftModelForCausalLM
from transformers import AutoTokenizer

OUTPUT_DIR = "qlora-bash-commands"        # your training folder — the one with all the files
MERGED_DIR = "qlora-bash-commands-merged"

tokenizer = AutoTokenizer.from_pretrained(OUTPUT_DIR)

merged_model = AutoPeftModelForCausalLM.from_pretrained(
    OUTPUT_DIR,
    device_map="auto",
    torch_dtype=torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16,
)
merged_model = merged_model.merge_and_unload()

merged_model.save_pretrained(MERGED_DIR)
tokenizer.save_pretrained(MERGED_DIR)
print("Merged model saved to:", MERGED_DIR)

import json

tok_cfg_path = "/content/qlora-bash-commands-merged/tokenizer_config.json"

with open(tok_cfg_path) as f:
    cfg = json.load(f)

if "extra_special_tokens" in cfg:
    del cfg["extra_special_tokens"]
    with open(tok_cfg_path, "w") as f:
        json.dump(cfg, f, indent=2)
    print("Patched: removed extra_special_tokens")
else:
    print("Nothing to patch")

# Commented out IPython magic to ensure Python compatibility.
# 2. Convert the merged model to a single GGUF file
!git clone --depth 1 https://github.com/ggml-org/llama.cpp
# %cd llama.cpp
!pip install -q -r requirements.txt

!python convert_hf_to_gguf.py /content/qlora-bash-commands-merged \
    --outfile /content/bash-commands-qwen2.5-1.5b.Q8_0.gguf \
    --outtype q8_0

# %cd /content

import shutil
from google.colab import files

# Define folders and zip filenames
folders_to_zip = {
    "qlora-bash-commands": "qlora-bash-commands.zip",
    "qlora-bash-commands-merged": "qlora-bash-commands-merged.zip"
}

# Compress each folder into a zip file
for folder, zip_filename in folders_to_zip.items():
    print(f"Zipping {folder}...")
    # shutil.make_archive automatically appends '.zip', so we pass the base name without the extension
    base_name = zip_filename.replace(".zip", "")
    shutil.make_archive(base_name, 'zip', folder)
    print(f"Created {zip_filename}")

# Trigger browser downloads for both zip files
for zip_filename in folders_to_zip.values():
    print(f"Downloading {zip_filename}...")
    files.download(zip_filename)